---
- name: Bootstrap
  hosts: localhost
  connection: local

  vars_prompt:
    - name: email
      prompt: What's your e-mail?
      private: false

    - name: setup_system
      prompt: Setup system (installs apps, …)? [y]/n
      private: false

    - name: setup_macos
      prompt: Setup macos? [y]/n
      private: false

    - name: setup_git
      prompt: Setup git? [y]/n
      private: false

    - name: setup_ohmyzsh
      prompt: Setup ohmyzsh? [y]/n
      private: false

    - name: setup_node
      prompt: Setup node? [y]/n
      private: false

  tasks:
    - name: Ensure ~/.config exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: Symlink configurations to ~/.config
      with_items:
        - nvim
        - tmux
        - ghostty
      ansible.builtin.file:
        src: "{{ playbook_dir }}/config/{{ item }}"
        path: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link

    - ansible.builtin.include_tasks: playbooks/system.yml
      when: setup_system != "n"

    - ansible.builtin.include_tasks: playbooks/macos.yml
      when: setup_macos != "n"

    - ansible.builtin.include_tasks: playbooks/git.yml
      when: setup_git != "n"

    - ansible.builtin.include_tasks: playbooks/ohmyzsh.yml
      when: setup_ohmyzsh != "n"

    - ansible.builtin.include_tasks: playbooks/node.yml
      when: setup_node != "n"
      vars:
        nvm: "v0.39.5"
        node: "v20.9.0"
