---
- name: Install git package
  community.general.homebrew:
    name: git
    state: present

- name: Setup git config
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Create git global gitignore file
  ansible.builtin.template:
    src: templates/gitignore.j2
    dest: "{{ ansible_env.HOME }}/.gitignore"
