---
- name: Install neovim package
  community.general.homebrew:
    name: neovim
    state: present

- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Symlink neovim folder to ~/.config/nvim
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/nvim"
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
