---
- name: Check for oh my zsh
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Install oh my zsh
  when: not ohmyzsh_dir.stat and not ohmyzsh_dir.stat.isdir
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh//custom/themes/powerlevel10k"
    depth: 1

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Configure zsh-autosuggestions plugin
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins=\('
    line: plugins=(git zsh-autosuggestions)

- name: Symlink aliases/exports/functions
  with_items:
    - aliases.zsh
    - exports.zsh
    - functions.zsh
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item }}"
    state: link
