---
- name: Check for oh my zsh
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/oh-my-zsh.sh"
  register: ohmyzsh_script

- name: Install oh my zsh
  when: not ohmyzsh_script.stat.exists
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh//custom/themes/powerlevel10k"
    depth: 1

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Symlink aliases/exports/functions
  with_items:
    - aliases.zsh
    - exports.zsh
    - functions.zsh
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item }}"
    state: link

- name: Ensure private exports file exist
  ansible.builtin.copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/private-exports.zsh"
    force: false
