---
- name: Symlink configurations to ~
  loop:
    - { src: 'p10k.zsh', dest: '.p10k.zsh' }
    - { src: 'zshrc', dest: '.zshrc' }
    - { src: 'aliases.zsh', dest: '.aliases' }
    - { src: 'exports.zsh', dest: '.exports' }
    - { src: 'functions.zsh', dest: '.functions' }
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/{{ item.src }}"
    path: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link

- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Symlink configurations to ~/.config
  with_items:
    - nvim
    - tmux
    - ghostty
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
