---
- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop:
    - bash
    - bc
    - coreutils
    - fastfetch
    - fzf
    - gawk
    - gh
    - git
    - git-delta
    - gnupg
    - httpie
    - jq
    - lazygit
    - neovim
    - nowplaying-cli
    - python3
    - ripgrep
    - stow
    - tldr
    - tmux
    - tree

- name: Install apps with brew
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - alfred
    - docker
    - ghostty
    - google-chrome
    - rectangle
    - slack
    - spotify
    - whatsapp

- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Ensure ~/work exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/work"
    state: directory

- name: Ensure ~/personal exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/personal"
    state: directory

- name: Clone my bin tools
  ansible.builtin.git:
    repo: https://github.com/danielcorreia/toolx.git
    dest: "{{ ansible_env.HOME }}/personal/bin"

- name: Ensure ~/.ssh exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Generate ssh key
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    passphrase: ""
    type: ed25519

- name: Setup ssh config
  ansible.builtin.template:
    src: templates/sshconfig.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"

