---
- name: Install tmux package
  community.general.homebrew:
    name: tmux
    state: present

- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Symlink tmux folder to ~/.config/tmux
  ansible.builtin.file:
    src: "{{ playbook_dir }}/config/tmux"
    path: "{{ ansible_env.HOME }}/.config/tmux"
    state: link
